
export let data = [
    { en: "dog", ru: "собака" },
    // Природа (23 слова)
    { en: "forest", ru: "лес" },
    { en: "river", ru: "река" },
    { en: "mountain", ru: "гора" },
    { en: "ocean", ru: "океан" },
    { en: "field", ru: "поле" },
    { en: "flower", ru: "цветок" },
    { en: "grass", ru: "трава" },
    { en: "leaf", ru: "лист" },
    { en: "cloud", ru: "облако" },
    { en: "rain", ru: "дождь" },
    { en: "snow", ru: "снег" },
    { en: "wind", ru: "ветер" },
    { en: "star", ru: "звезда" },
    { en: "moon", ru: "луна" },
    { en: "sky", ru: "небо" },
    { en: "earth", ru: "земля" },
    { en: "stone", ru: "камень" },
    { en: "island", ru: "остров" },
    { en: "beach", ru: "пляж" },
    { en: "wave", ru: "волна" },
    { en: "season", ru: "время года" },
    { en: "thunder", ru: "гром" },
    { en: "lightning", ru: "молния" },

    // Город и инфраструктура (22 слова)
    { en: "street", ru: "улица" },
    { en: "building", ru: "здание" },
    { en: "bridge", ru: "мост" },
    { en: "park", ru: "парк" },
    { en: "hospital", ru: "больница" },
    { en: "school", ru: "школа" },
    { en: "university", ru: "университет" },
    { en: "restaurant", ru: "ресторан" },
    { en: "cafe", ru: "кафе" },
    { en: "market", ru: "рынок" },
    { en: "square", ru: "площадь" },
    { en: "station", ru: "станция" },
    { en: "airport", ru: "аэропорт" },
    { en: "hotel", ru: "отель" },
    { en: "bank", ru: "банк" },
    { en: "pharmacy", ru: "аптека" },
    { en: "library", ru: "библиотека" },
    { en: "museum", ru: "музей" },
    { en: "theater", ru: "театр" },
    { en: "factory", ru: "фабрика" },
    { en: "road", ru: "дорога" },
    { en: "traffic", ru: "движение" },

    // Еда и напитки (21 слово)
    { en: "bread", ru: "хлеб" },
    { en: "cheese", ru: "сыр" },
    { en: "meat", ru: "мясо" },
    { en: "fish", ru: "рыба" },
    { en: "fruit", ru: "фрукт" },
    { en: "vegetable", ru: "овощ" },
    { en: "soup", ru: "суп" },
    { en: "salad", ru: "салат" },
    { en: "cake", ru: "торт" },
    { en: "chocolate", ru: "шоколад" },
    { en: "coffee", ru: "кофе" },
    { en: "tea", ru: "чай" },
    { en: "juice", ru: "сок" },
    { en: "milk", ru: "молоко" },
    { en: "butter", ru: "масло" },
    { en: "egg", ru: "яйцо" },
    { en: "rice", ru: "рис" },
    { en: "salt", ru: "соль" },
    { en: "sugar", ru: "сахар" },
    { en: "potato", ru: "картофель" },
    { en: "tomato", ru: "помидор" },

    // Эмоции и чувства (15 слов)
    { en: "happy", ru: "счастливый" },
    { en: "sad", ru: "грустный" },
    { en: "angry", ru: "злой" },
    { en: "afraid", ru: "испуганный" },
    { en: "excited", ru: "взволнованный" },
    { en: "bored", ru: "скучающий" },
    { en: "tired", ru: "уставший" },
    { en: "surprised", ru: "удивлённый" },
    { en: "calm", ru: "спокойный" },
    { en: "proud", ru: "гордый" },
    { en: "love", ru: "любовь" },
    { en: "joy", ru: "радость" },
    { en: "fear", ru: "страх" },
    { en: "hope", ru: "надежда" },
    { en: "shy", ru: "застенчивый" },

    // Технологии (15 слов)
    { en: "computer", ru: "компьютер" },
    { en: "keyboard", ru: "клавиатура" },
    { en: "mouse", ru: "мышь" },
    { en: "screen", ru: "экран" },
    { en: "internet", ru: "интернет" },
    { en: "website", ru: "веб-сайт" },
    { en: "password", ru: "пароль" },
    { en: "email", ru: "электронная почта" },
    { en: "file", ru: "файл" },
    { en: "data", ru: "данные" },
    { en: "app", ru: "приложение" },
    { en: "video", ru: "видео" },
    { en: "audio", ru: "аудио" },
    { en: "download", ru: "скачивать" },
    { en: "upload", ru: "загружать" },

    // Спорт и активность (15 слов)
    { en: "sport", ru: "спорт" },
    { en: "game", ru: "игра" },
    { en: "team", ru: "команда" },
    { en: "player", ru: "игрок" },
    { en: "coach", ru: "тренер" },
    { en: "goal", ru: "гол" },
    { en: "ball", ru: "мяч" },
    { en: "race", ru: "гонка" },
    { en: "swim", ru: "плавать" },
    { en: "run", ru: "бегать" },
    { en: "jump", ru: "прыгать" },
    { en: "cycle", ru: "ездить на велосипеде" },
    { en: "win", ru: "побеждать" },
    { en: "lose", ru: "проигрывать" },
    { en: "score", ru: "счёт" }
];
/* текст выходит за кнопку  */